## Numpy Hands On

1. Create a numpy array with numpy.array module and with a data type integer and float.


In [1]:
import numpy as np

In [7]:
# 1

arr1=np.array([1,2,3,4])
arr2=np.array([1.2,2.0,3.4])

print(arr1.dtype)
print(arr2.dtype)

int32
float64


In [12]:
# 2

arr1=np.array([1,2,3,4], dtype='int')
arr2=np.array([1,2,3], dtype='float')

print(arr1.dtype)
print(arr2.dtype)

arr2

int32
float64


array([1., 2., 3.])

2. Create numpy arrays that have zero, one, two, three, Four dimensions respectively.
Also, print the shape and dimensions of the numpy arrays created above.

In [21]:
a0 = np.array(1) 
print(np.ndim(a0))

a1 =np.array([1,2,3,4,5])
print(np.ndim(a1))

# a2

# a3

# a4

0
1


In [23]:
a0 = np.array(1)
print(np.ndim(a0))

a1 = np.array([1])
print(np.ndim(a1))

a2 = np.array([2])
print(np.ndim(a2))

a3 = np.array([3])
print(np.ndim(a3))

a4 = np.array([4])
print(np.ndim(a4))


print(a1)

0
1
1
1
1
[1]


In [30]:
a0 = np.array(1)
print(np.ndim(a0))

a1 = np.array([1,2,3])
print(np.ndim(a1))

a2 = np.array([[1,2],[3,4]])
print(np.ndim(a2))

a3 = np.array([[[1,2],[3,4],[5,6]]])
print(np.ndim(a3))

a4 = np.array([[[[1,2],[3,4],[5,6],[7,8]]]])
print(np.ndim(a4))


0
1
2
3
4


3. Create a 2x2, 3x3, and 4x4 identity matrix using numpy.

In [34]:
# 1

a2=np.identity(2, dtype='int')
print(a2)

a3=np.identity(3, dtype='int')
print()
print(a3)

a4=np.identity(4, dtype='int')
print()
print(a4)


[[1 0]
 [0 1]]

[[1 0 0]
 [0 1 0]
 [0 0 1]]

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [35]:
# 2

a2 = np.identity(2)
print(a2)

a3 = np.identity(3)
print()
print(a3)

a4 = np.identity(4)
print()
print(a4)


[[1. 0.]
 [0. 1.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [38]:
# 3

dimension = int(input("Enter the dimension of identitiy matrix: "))

identity_matrix = np.identity(dimension, dtype="int")
print(identity_matrix)


Enter the dimension of identitiy matrix: 7
[[1 0 0 0 0 0 0]
 [0 1 0 0 0 0 0]
 [0 0 1 0 0 0 0]
 [0 0 0 1 0 0 0]
 [0 0 0 0 1 0 0]
 [0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1]]


4. Create a numpy array with shape 2x5 that has all the elements as zero.


In [48]:
arr = np.zeros([2,5])

print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [49]:
arr = np.zeros([2,5], dtype='int')

print(arr)

[[0 0 0 0 0]
 [0 0 0 0 0]]


In [50]:
arr1 = np.full([2,5], 0)

print(arr1)

[[0 0 0 0 0]
 [0 0 0 0 0]]


In [53]:
row = int(input('Enter no of rows: '))

column = int(input('Enter no of columns: '))

n= int(input('Enter the element: '))

arr= np.full([row,column], n)

print(arr)

Enter no of rows: 5
Enter no of columns: 6
Enter the element: 5
[[5 5 5 5 5 5]
 [5 5 5 5 5 5]
 [5 5 5 5 5 5]
 [5 5 5 5 5 5]
 [5 5 5 5 5 5]]


5. Create a numpy array that has the shape 3x5 and all the elements are 5

In [54]:
ar = np.full([3,5],5)
print(ar)

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


In [55]:
s2 = np.ones((3,5))*5

print(s2)


[[5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]]


In [56]:
row = int(input('Enter no of rows: '))

column = int(input('Enter no of columns: '))

n= int(input('Enter the element: '))

arr= np.full([row,column], n)

print(arr)

Enter no of rows: 3
Enter no of columns: 5
Enter the element: 5
[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


6. Create a numpy array with random integers in the range 0-100, and the sample size
should be 25.


In [60]:
arr = np.random.randint(0,101,size=25)
print(arr)
print(len(arr))

[ 9 79 63 26 58 49 14 39 42 96 33 52 74 71  6 77  3 67 92 51  6 94  9 88
 43]
25


7. Create a numpy array with a shape 3x3 that has all elements as 1.

In [62]:
# 1

arr = np.ones([3,3], dtype='int')
print(arr)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [63]:
# 2

arr = np.full([3,3], 1)
print(arr)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


8. Create a numpy array in the shape 2x3 with random integers in the range 0-100.
Reshape the array in the shape 3x2 and print the updated shape of the resultant array.

In [74]:
# 1

arr = np.random.randint(0,101, size=[2,3])
print(arr)
print()

arr1=arr.reshape(3,2)
print(arr1)

[[57 32 82]
 [77 10 90]]

[[57 32]
 [82 77]
 [10 90]]


In [75]:
# 2

row = int(input("Enter the no. of rows: "))

column = int(input("Enter the no. of columns: "))

arr1 = np.random.randint(0,100,(row,column))
print("\n",arr1)

arr2 =arr1.reshape(column,row)
print("\n",arr2)

print("\nShape of resultant array: ",arr2.shape)


Enter the no. of rows: 2
Enter the no. of columns: 3

 [[56 41 18]
 [27 74 55]]

 [[56 41]
 [18 27]
 [74 55]]

Shape of resultant array:  (3, 2)


9. Create a random array, with the range 0-1000, with a size 50. Perform the
following operations on the same.

a. Print the first ten elements of the array.

b. Print the last ten elements of the array

c. Print the elements from the indexes 10-25

d. Print the element at the index 22

e. Print the array using negative indexing.

f. Print the last ten elements of the array, using negative indexing.


In [82]:
randarr = np.random.randint(0,1001, size=50)
print(randarr)



[266 587  82 384  11 989 645 118 911 842  26 347 938 440 716 114 878 958
 246 177 583  87 253 214 279  60 319 198 156 947 510 632 764 591 876 757
 418 690 897  47  51 964 658 723 618 590 613 113 308 688]


In [83]:
# a. Print the first ten elements of the array.

print(randarr[0:10])


[266 587  82 384  11 989 645 118 911 842]


In [84]:
# b. Print the last ten elements of the array

print(randarr[40:])

# print(randarr[-10:])


[ 51 964 658 723 618 590 613 113 308 688]


In [85]:
# c. Print the elements from the indexes 10-25

print(randarr[10:26])


[ 26 347 938 440 716 114 878 958 246 177 583  87 253 214 279  60]


In [86]:
# d. Print the element at the index 22

print(randarr[22])


253


In [88]:
# e. Print the array using negative indexing.

print(randarr[-50:])


[266 587  82 384  11 989 645 118 911 842  26 347 938 440 716 114 878 958
 246 177 583  87 253 214 279  60 319 198 156 947 510 632 764 591 876 757
 418 690 897  47  51 964 658 723 618 590 613 113 308 688]


In [89]:
# f. Print the last ten elements of the array, using negative indexing.

print(randarr[-10:])

[ 51 964 658 723 618 590 613 113 308 688]


10. Given a numpy array that has values = [1,2,3,4,5]. Perform the following operations.

a. Insert the element 6 at the end of the array.

b. Insert the element 10 at the beginning of the array.

c. Insert the element 30, before 4.

d. Update the element 5 as 50.

e. Delete the element 50 in the updated array.

f. Create a function to search for the element 30.

g. Sort the array in ascending order

In [97]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [ ]:
np.append()
np.insert()
np.delete()
.sort()

In [98]:
# a. Insert the element 6 at the end of the array.

arr=np.append(arr, 6)

In [99]:
arr

array([1, 2, 3, 4, 5, 6])

In [100]:
# b. Insert the element 10 at the beginning of the array.

arr=np.insert(arr, 0, 10)
print(arr)

[10  1  2  3  4  5  6]


In [101]:
# c. Insert the element 30, before 4.

arr=np.insert(arr, 4, 30)
print(arr)

[10  1  2  3 30  4  5  6]


In [103]:
# d. Update the element 5 as 50.

arr[6] = 50

In [104]:
print(arr)

[10  1  2  3 30  4 50  6]


In [105]:
# e. Delete the element 50 in the updated array.

arr=np.delete(arr, -2)
print(arr)

[10  1  2  3 30  4  6]


In [106]:
# f. Create a function to search for the element 30.

def search(n):
    
    for i in range(len(arr)):
        if arr[i]==n:
            return i

In [110]:
index=search(30)

print('Found at index: ',index)

Found at index:  4


In [116]:
# g. Sort the array in ascending order


arr.sort()
print(arr)

[ 1  2  3  4  6 10 30]
